version: '3'

services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5042:5042"
    links:
      - db
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/
    links:
      - web
